package models

// API user credentials
// It is used to sign in
//
// swagger:model user
type User struct {
	// User's name
	//
	// required: true
	UserName string `json:"user_name"`
	// User's password
	//
	// required: true
	Password string `json:"password"`
}

// API user credentials Response
// It is used to check the credentials persisted
// swagger:model user
type UserResponse struct {
	//User's ID
	//
	//AutoGenerated:true
	Id string `json:"_id"`
	// User's name
	//
	// required: true
	UserName string `json:"user_name"`
	// User's password
	//
	// required: true
	Password string `json:"password"`
}
